version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5555:5555"
    volumes:
      - ./backend/app:/server/app
    environment:
      - FLASK_ENV=development  

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/client/src
      - ./frontend/public:/client/public
      - ./frontend/package.json:/client/package.json
      - ./frontend/package-lock.json:/client/package-lock.json
    environment:
      - CHOKIDAR_USEPOLLING=true
