services:
  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  web:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
