"""Add google_id to users

Revision ID: 4091cda7e987
Revises: 40ecedc3bbbd
Create Date: 2024-10-18 09:35:00.594358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4091cda7e987'
down_revision = '40ecedc3bbbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
