name: CI

on:
  push:
    branches:
      - main
      - dev-eustache

  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Flask Docker image
        run: |
          docker build -t hrs-flask-app -f server/Dockerfile .

      - name: Build Vite Docker image
        run: |
          docker build -t hrs-vite-app -f client/Dockerfile .

      - name: Run application using Honcho
        run: |
          # Start the containers in the background
          docker run -d --name flask-container hrs-flask-app
          docker run -d --name vite-container hrs-vite-app
          
          # Give the services a moment to start
          sleep 10

          # Run Honcho to manage both services
          honcho start -f Procfile.dev
